"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "ne";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

// Translation data
const translations = {
  en: {
    // Navigation
    "nav.login": "Login",
    "nav.signup": "Sign Up",
    "nav.admin": "Admin",
    "nav.welcome": "Welcome",

    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.saving": "Saving...",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.back": "Back",
    "common.next": "Next",
    "common.submit": "Submit",
    "common.close": "Close",
    "common.yes": "Yes",
    "common.no": "No",
    "common.confirm": "Confirm",
    "common.unknown": "Unknown",

    // Auth
    "auth.login": "Login",
    "auth.signup": "Sign Up",
    "auth.logout": "Logout",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.name": "Name",
    "auth.mobile": "Mobile Number",
    "auth.confirmPassword": "Confirm Password",
    "auth.forgotPassword": "Forgot Password?",
    "auth.rememberMe": "Remember Me",
    "auth.dontHaveAccount": "Don't have an account?",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.signUpHere": "Sign up here",
    "auth.loginHere": "Login here",
    "auth.welcomeBack": "Welcome Back to",
    "auth.joinThe": "Join the",
    "auth.valleyAdventure": "Valley Adventure",
    "auth.createAccountMessage":
      "Create your account and start exploring the beautiful valleys of Nepal on two wheels.",
    "auth.bicycleAdventureImage": "Bicycle Adventure Image",
    "auth.exploringValleys": "People exploring valleys on bikes",
    "auth.joinValleyAdventure": "Join the Valley Adventure",
    "auth.createAccountToStart": "Create your account to get started",
    "auth.byCreatingAccount": "By creating an account, you agree to our",
    "auth.termsOfService": "Terms of Service",
    "auth.and": "and",
    "auth.privacyPolicy": "Privacy Policy",

    // Homepage
    "home.title": "Welcome to PedalNepal",
    "home.subtitle": "Your trusted bike rental service",
    "home.getStarted": "Get Started",
    "home.learnMore": "Learn More",
    "home.features": "Features",
    "home.about": "About",
    "home.contact": "Contact",
    "home.exploreNepal": "Explore Nepal",
    "home.onTwoWheels": "on Two Wheels",
    "home.description":
      "Discover the breathtaking valleys, ancient temples, and vibrant culture of Nepal through our premium bike rental service.",
    "home.adventureAwaits": "Adventure awaits at every turn!",
    "home.manageActiveRental": "Manage Active Rental",
    "home.activeRental": "Active Rental:",
    "home.rentalOverdue":
      "Your rental is {hours} hour(s) overdue. Please end your current ride first.",
    "home.hasActiveRental":
      "You have an active rental. Please end your current ride first.",
    "home.dailyRentalOverdue":
      "Your daily rental is {hours} hour(s) overdue. Please end your current ride first.",
    "home.hasActiveDailyRental":
      "You have an active daily rental. Please end your current ride first.",
    "home.payAsYouGoOverdue":
      "Your pay-as-you-go rental is {hours} hour(s) overdue. Please end your current ride first.",
    "home.hasActivePayAsYouGo":
      "You have an active pay-as-you-go rental. Please end your current ride first.",
    "home.redirectingToAdmin": "Redirecting to admin dashboard...",

    // Bike Selection
    "bike.title": "Select Your Bike",
    "bike.available": "Available",
    "bike.occupied": "Occupied",
    "bike.reserved": "Reserved",
    "bike.maintenance": "Under Maintenance",
    "bike.rate": "Rate",
    "bike.perHour": "per hour",
    "bike.selectSlot": "Select Slot",
    "bike.rentBike": "Rent Bike",
    "bike.slot": "Slot",
    "bike.availableBikes": "Available Bikes",
    "bike.findPerfectRide": "Find your perfect ride for exploring valley",
    "bike.availableSlots": "Available Slots",
    "bike.rentNow": "Rent Now",
    "bike.yourCredits": "Your Credits",
    "bike.station": "Station",
    "bike.km": "km",
    "bike.perDay": "/day",

    // Bike Selection
    "bikeSelection.title": "Select Your Bike",
    "bikeSelection.station": "Station",
    "bikeSelection.selectSlot": "Select a slot to rent a bike",
    "bikeSelection.rentalDuration": "Rental Duration",
    "bikeSelection.hourly": "Hourly",
    "bikeSelection.daily": "Daily",
    "bikeSelection.payAsYouGo": "Pay as you go",
    "bikeSelection.hours": "Hours",
    "bikeSelection.hour": "Hour",
    "bikeSelection.termsAgreement": "I agree to the terms and conditions",
    "bikeSelection.confirmRental": "Confirm Rental",
    "bikeSelection.cancel": "Cancel",
    "bikeSelection.slot": "Slot",
    "bikeSelection.available": "Available",
    "bikeSelection.occupied": "Occupied",
    "bikeSelection.reserved": "Reserved",
    "bikeSelection.maintenance": "Under Maintenance",
    "bikeSelection.chooseSlots": "Choose from available slots",
    "bikeSelection.selectRentalOption": "Select Rental Option",
    "bikeSelection.flexiRide": "Flexi Ride",
    "bikeSelection.payOnlyForTimeUsed": "Pay only for time used",
    "bikeSelection.fixedRide": "Fixed Ride",
    "bikeSelection.prepaidHourlyRental": "Pre-paid hourly rental",
    "bikeSelection.selectNumberOfHours": "Select Number of Hours",
    "bikeSelection.quickSelect": "Quick select",
    "bikeSelection.upfrontCost": "Upfront Cost",
    "bikeSelection.rate": "Rate",
    "bikeSelection.chargedWhenRideEnds": "charged when ride ends",
    "bikeSelection.noUpfrontPaymentRequired":
      "No upfront payment required! Pay only for the time you use.",
    "bikeSelection.rentalPrice": "Rental Price",
    "bikeSelection.yourCredits": "Your Credits",
    "bikeSelection.remainingCredits": "Remaining Credits",
    "bikeSelection.insufficientCredits": "Insufficient credits! You need",
    "bikeSelection.forThisRental": "for this rental",
    "bikeSelection.minimumCreditsRequired":
      "Minimum रू25 credits required for hourly rentals.",
    "bikeSelection.safetyNotes": "Safety Notes",
    "bikeSelection.safetyNote1":
      "Always wear a helmet and follow local traffic rules.",
    "bikeSelection.safetyNote2": "Check brakes, tires before riding.",
    "bikeSelection.safetyNote3":
      "Ride only in safe, permitted areas; obey all signage.",
    "bikeSelection.termsAndCondition": "Terms & Condition",
    "bikeSelection.termsNote1":
      "Pedal Nepal is not responsible for accidents, injuries, or damages from bicycle use.",
    "bikeSelection.termsNote2":
      "Riders assume all risks and are responsible for fines/legal consequences of unsafe or unlawful riding.",
    "bikeSelection.termsNote3":
      "The company does not guarantee availability, performance, or uninterrupted service.",
    "bikeSelection.agreeToTerms":
      "I have read and agreed to all the safety notes and terms presented",
    "bikeSelection.termsAcknowledgment":
      "By checking this box, you acknowledge that you understand the safety requirements and accept all terms and conditions of the rental service.",
    "bikeSelection.pleaseAgreeToTerms": "Please Agree to Terms",

    // Rental
    "rental.confirm": "Confirm Rental",
    "rental.details": "Rental Details",
    "rental.startTime": "Start Time",
    "rental.endTime": "End Time",
    "rental.duration": "Duration",
    "rental.cost": "Cost",
    "rental.confirmRental": "Confirm Rental",
    "rental.rentalConfirmed": "Rental Confirmed",
    "rental.rentalSuccess": "Your rental has been confirmed!",

    // Return Bike
    "return.title": "Return Bike",
    "return.selectStation": "Select Station",
    "return.selectSlot": "Select Return Slot",
    "return.availableForReturn": "Available for Return",
    "return.endRide": "End My Ride",
    "return.returnConfirmed": "Return Confirmed",
    "return.returnSuccess": "Your bike has been returned successfully!",
    "return.rentAnother": "Rent Another Bike",
    "return.goHome": "Go to Home",
    "return.returnLocation": "Return Location",
    "return.deductedFromCredits": "Deducted from your credits",
    "return.remainingCredits": "Remaining Credits",
    "return.thankYouMessage": "Thank you for using pedalNepal!",
    "return.additionalInfo":
      "Your bike has been safely returned. You can now rent another bike from any station or check your ride history in your profile.",

    // My Rentals
    "rentals.title": "My Rentals",
    "rentals.history": "Rental History",
    "rentals.activeRentals": "Active Rentals",
    "rentals.completedRentals": "Completed Rentals",
    "rentals.noRentals": "No rentals found",
    "rentals.status": "Status",
    "rentals.active": "Active",
    "rentals.completed": "Completed",
    "rentals.cancelled": "Cancelled",
    "rentals.loadingRentals": "Loading your rentals...",
    "rentals.noRentalsYet": "No Rentals Yet",
    "rentals.noRentalsMessage":
      "You haven't rented any bikes yet. Start your adventure today!",
    "rentals.rentABike": "Rent a Bike",
    "rentals.trackActivities": "Track your bike rental activities",
    "rentals.totalSpent": "Total Spent",
    "rentals.recentTop5": "Recent Top 5",
    "rentals.totalRentals": "Total Rentals",
    "rentals.allRentals": "All Rentals",
    "rentals.recent": "Recent",
    "rentals.rentalId": "Rental ID",
    "rentals.locationDetails": "Location Details",
    "rentals.rentalInfo": "Rental Info",
    "rentals.period": "Period",
    "rentals.timeAndCost": "Time & Cost",
    "rentals.showing": "Showing",
    "rentals.to": "to",
    "rentals.of": "of",
    "rentals.rentals": "rentals",
    "rentals.rentAnotherBike": "Rent Another Bike",
    "rentals.hour": "Hour",
    "rentals.hours": "Hours",
    "rentals.calculatedOnReturn": "calculated on return",
    "rentals.overdue": "Overdue",
    "rentals.totalPayment": "Total Payment",
    "rentals.paymentAmount": "Payment Amount",

    // Admin Dashboard
    "admin.dashboard": "Admin Dashboard",
    "admin.overview": "Overview",
    "admin.users": "Users",
    "admin.stations": "Stations",
    "admin.reviews": "Reviews",
    "admin.bicycles": "Bicycles",
    "admin.addUser": "Add User",
    "admin.addStation": "Add Station",
    "admin.manageSlots": "Manage Slots",
    "admin.totalUsers": "Total Users",
    "admin.activeUsers": "Active Users",
    "admin.totalStations": "Total Stations",
    "admin.totalBikes": "Total Bikes",
    "admin.availableBikes": "Available Bikes",
    "admin.rentedBikes": "Rented Bikes",
    "admin.maintenanceBikes": "Under Maintenance",
    "admin.reservedSlots": "Reserved Slots",
    "admin.reviewsComplaints": "Reviews & Complaints",
    "admin.addNewUser": "Add New User",
    "admin.createNewUserAccount": "Create a new user account",
    "admin.userInformation": "User Information",
    "admin.fillUserDetails": "Fill in the details to create a new user account",
    "admin.username": "Username",
    "admin.enterUsername": "Enter username",
    "admin.enterEmail": "Enter email address",
    "admin.enterPassword": "Enter password",
    "admin.enterMobile": "Enter mobile number",
    "admin.fullName": "Full Name",
    "admin.enterFullName": "Enter full name",
    "admin.regularUser": "Regular User",
    "admin.administrator": "Administrator",
    "admin.creating": "Creating...",
    "admin.createUser": "Create User",
    "admin.mobileExists": "Mobile number already exists!",
    "admin.userCreated": "User created successfully!",
    "admin.createUserFailed": "Failed to create user",
    "admin.addNewStation": "Add New Station",
    "admin.manageStationsAndPricing": "Manage stations and pricing",
    "admin.manageStations": "Manage Stations",
    "admin.stationInformation": "Station Information",
    "admin.fillStationDetails": "Fill in the details to create a new station",
    "admin.enterStationName": "Enter station name",
    "admin.enterLocation": "Enter location",
    "admin.numberOfBikes": "Number of Bikes",
    "admin.enterNumberOfBikes": "Enter number of bikes",
    "admin.bikesToAdd": "Number of bikes to add to this station (1-50)",
    "admin.initialStatus": "Initial Status",
    "admin.allBikesAvailable": "All bikes start as available",
    "admin.setPricingForStation": "Set Pricing for This Station",
    "admin.hourlyRate": "Hourly Rate",
    "admin.dailyRate": "Daily Rate",
    "admin.cancelEdit": "Cancel Edit",
    "admin.updating": "Updating...",
    "admin.updateStation": "Update Station",
    "admin.createStation": "Create Station",
    "admin.manageSlotsAndPricing":
      "Manage slots, pricing, and station operations",
    "admin.resetToDefaults": "Reset to Defaults",
    "admin.defaultPricing": "Default: रू25/hour, रू250/day",
    "admin.saveAllChanges": "Save All Changes",
    "admin.confirmDeleteStation":
      'Are you sure you want to delete station "{stationName}" and all its bikes?',
    "admin.stationDeleted": "Station deleted successfully!",
    "admin.deleteStationFailed": "Failed to delete station. Please try again.",
    "admin.stationUpdated": "Station updated successfully!",
    "admin.stationCreated": "Station created successfully!",
    "admin.createStationFailed": "Failed to create station. Please try again.",
    "admin.totalRentals": "Total Rentals",
    "admin.recentActivity": "Recent Activity",
    "admin.newUserRegistered": "New user registered",
    "admin.allStatus": "All Status",
    "admin.inactiveUsers": "Inactive Users",
    "admin.adminUsers": "Admin Users",
    "admin.statusActive": "Active",
    "admin.statusInactive": "Inactive",
    "admin.statusAdmin": "Admin",
    "admin.bikeStatusTitle": "All Stations Bike Status",
    "admin.bikeStatusDescription": "Total bikes across all stations",
    "admin.userActivityTitle": "User Activity",
    "admin.userActivityDescription": "User engagement breakdown",
    "admin.userManagement": "User Management",
    "admin.stationManagement": "Station Management",
    "admin.serialNumber": "SN",
    "admin.name": "Name",
    "admin.status": "Status",
    "admin.rides": "Rides",
    "admin.station": "Station",
    "admin.duration": "Duration",
    "admin.credits": "Credits",
    "admin.spent": "Spent",
    "admin.actions": "Actions",
    "admin.stationName": "Station Name",
    "admin.location": "Location",
    "admin.totalSlots": "Total Slots",
    "admin.inMaintenance": "In Maintenance",
    "admin.availableSlots": "Available Slots",
    "admin.loadingDashboard": "Loading Admin Dashboard...",
    "admin.accessDenied": "Access Denied",
    "admin.noPermission":
      "You don't have permission to access the admin dashboard.",
    "admin.goToHome": "Go to Home",
    "admin.managePaddleNepal": "Manage PedalNepal",
    "admin.currentlyActive": "currently active",
    "admin.emptySlots": "Empty Slots",
    "admin.rented": "Rented",
    "admin.empty": "Empty",
    "admin.available": "Available",
    "admin.filterByName": "Filter by Name",
    "admin.filterByStatus": "Filter by Status",
    "admin.filterByNameLocation": "Filter by Name/Location",
    "admin.add": "Add",
    "admin.admin": "Admin",
    "admin.remove": "Remove",
    "admin.delete": "Delete",
    "admin.edit": "Edit",
    "admin.addCredits": "Add Credits",
    "admin.addCreditsToUser": "Add credits to user account",
    "admin.creditsToAdd": "Credits to Add",
    "admin.currentCredits": "Current Credits",
    "admin.newBalance": "New Balance",
    "admin.addCreditsButton": "Add Credits",
    "admin.cancel": "Cancel",
    "admin.maintenance": "Maintenance",
    "admin.noStationsFound": "No Stations Found",
    "admin.noStationsMessage": "No stations available matching your filters.",
    "admin.returningUsers": "Returning Users",
    "admin.newUsers": "New Users",
    "admin.manageSlotsTitle": "Manage slots",
    "admin.editStationTitle": "Edit station",
    "admin.deleteStationTitle": "Delete station",
    "admin.perHour": "per hour",
    "admin.perDay": "per day",
    "admin.slotStatus": "Slot Status",
    "admin.occupied": "Occupied",
    "admin.currentPricing": "Current Pricing",
    "admin.hourly": "Hourly",
    "admin.daily": "Daily",

    // User Management
    "users.title": "User Management",
    "users.addUser": "Add New User",
    "users.editUser": "Edit User",
    "users.deleteUser": "Delete User",
    "users.name": "Name",
    "users.email": "Email",
    "users.role": "Role",
    "users.status": "Status",
    "users.actions": "Actions",
    "users.admin": "Admin",
    "users.user": "User",
    "users.active": "Active",
    "users.inactive": "Inactive",

    // Station Management
    "stations.title": "Station Management",
    "stations.addStation": "Add New Station",
    "stations.editStation": "Edit Station",
    "stations.deleteStation": "Delete Station",
    "stations.name": "Station Name",
    "stations.location": "Location",
    "stations.address": "Address",
    "stations.slots": "Slots",
    "stations.actions": "Actions",

    // Slot Management
    "slots.title": "Slot Management",
    "slots.available": "Available",
    "slots.occupied": "Occupied",
    "slots.reserved": "Reserved for Returns",
    "slots.maintenance": "Under Maintenance",
    "slots.changeStatus": "Change Status",
    "slots.resetSlots": "Reset to 10 Slots",
    "slots.confirmStatusChange": "Are you sure you want to change the status?",
    "slots.confirmReset": "Are you sure you want to reset all slots?",

    // Reviews Management
    "reviews.title": "Reviews Management",
    "reviews.all": "All",
    "reviews.reviews": "Reviews",
    "reviews.complaints": "Complaints",
    "reviews.search": "Search reviews...",
    "reviews.rating": "Rating",
    "reviews.comment": "Comment",
    "reviews.type": "Type",
    "reviews.date": "Date",
    "reviews.noReviews": "No reviews found",
    "reviews.manageFeedback": "Manage customer feedback and complaints",
    "reviews.searchReviews": "Search reviews and complaints...",
    "reviews.user": "User",
    "reviews.station": "Station",
    "reviews.actions": "Actions",
    "reviews.view": "View",
    "reviews.reply": "Reply",
    "reviews.review": "Review",
    "reviews.complaint": "Complaint",

    // Language
    "language.english": "English",
    "language.nepali": "नेपाली",
    "language.switch": "Switch Language",

    // Profile
    "profile.activeUser": "Active User",
    "profile.personalInformation": "Personal Information",
    "profile.name": "Name",
    "profile.email": "Email",
    "profile.mobile": "Mobile",
    "profile.credits": "Credits",
    "profile.rentalsAvailable": "rentals available",
    "profile.changePassword": "Change Password",
    "profile.oldPassword": "Old password",
    "profile.newPassword": "New password",
    "profile.updateSuccess": "Profile updated successfully!",
    "profile.updateFailed": "Failed to update profile. Please try again.",
    "profile.updateError": "An error occurred. Please try again.",
    "profile.fillBothFields": "Please fill in both fields.",
    "profile.passwordChanged": "Password changed successfully!",
    "profile.oldPasswordIncorrect": "Old password incorrect.",
    "profile.digitalWallet": "Digital Wallet",
    "profile.manageWallet": "Manage Wallet",
    "profile.availableBalance": "Available Balance",

    // Footer
    "footer.home": "Home",
    "footer.wallet": "Wallet (Coming Soon)",
    "footer.myRentals": "My Rentals",
    "footer.qrScanner": "QR Scanner",
    "footer.availableBikes": "Available Bikes",
    "footer.profile": "Profile",
    "footer.logout": "Logout",
    "footer.digitalWallet": "Digital Wallet",
    "footer.managePaymentMethods": "Manage your payment methods",
    "footer.availableBalance": "Available Balance",
    "footer.addMoney": "Add Money",
    "footer.transactionHistory": "Transaction History",
    "footer.scanBikeQRCode": "Scan bike QR code to rent",
    "footer.startingCamera": "Starting camera...",
    "footer.cameraError": "Camera Error",
    "footer.tryAgain": "Try Again",
    "footer.cameraReadyToScan": "Camera ready to scan",
    "footer.scanning": "Scanning...",
    "footer.stopScanning": "Stop Scanning",
    "footer.startCamera": "Start Camera",
    "footer.selectStationManually": "Select Station Manually",

    // Error
    "error.somethingWentWrong": "Something went wrong!",
    "error.unexpectedError":
      "We're sorry, but something unexpected happened while loading this page.",
    "error.tryAgain": "Try again",
    "error.goToHome": "Go to Home",
    "error.errorDetails": "Error Details (Development)",
  },
  ne: {
    // Navigation
    "nav.login": "लगइन",
    "nav.signup": "साइन अप",
    "nav.admin": "एडमिन",
    "nav.welcome": "स्वागत छ",

    // Common
    "common.loading": "लोड हुँदै...",
    "common.error": "त्रुटि",
    "common.success": "सफल",
    "common.cancel": "रद्द गर्नुहोस्",
    "common.save": "सुरक्षित गर्नुहोस्",
    "common.saving": "सुरक्षित गर्दै...",
    "common.delete": "मेटाउनुहोस्",
    "common.edit": "सम्पादन गर्नुहोस्",
    "common.back": "फिर्ता",
    "common.next": "अर्को",
    "common.submit": "पेश गर्नुहोस्",
    "common.close": "बन्द गर्नुहोस्",
    "common.yes": "हो",
    "common.no": "होइन",
    "common.confirm": "पुष्टि गर्नुहोस्",
    "common.unknown": "अज्ञात",

    // Auth
    "auth.login": "लगइन",
    "auth.signup": "साइन अप",
    "auth.logout": "लगआउट",
    "auth.email": "इमेल",
    "auth.password": "पासवर्ड",
    "auth.name": "नाम",
    "auth.mobile": "मोबाइल नम्बर",
    "auth.confirmPassword": "पासवर्ड पुष्टि गर्नुहोस्",
    "auth.forgotPassword": "पासवर्ड बिर्सनुभयो?",
    "auth.rememberMe": "मलाई सम्झनुहोस्",
    "auth.dontHaveAccount": "खाता छैन?",
    "auth.alreadyHaveAccount": "पहिले नै खाता छ?",
    "auth.signUpHere": "यहाँ साइन अप गर्नुहोस्",
    "auth.loginHere": "यहाँ लगइन गर्नुहोस्",
    "auth.welcomeBack": "फिर्ता स्वागत छ",
    "auth.joinThe": "सामेल हुनुहोस्",
    "auth.valleyAdventure": "घाटी साहसिक",
    "auth.createAccountMessage":
      "आफ्नो खाता सिर्जना गर्नुहोस् र नेपालको सुन्दर घाटीहरू दुई पाङ्ग्रामा अन्वेषण गर्न सुरु गर्नुहोस्।",
    "auth.bicycleAdventureImage": "साइकल साहसिक छवि",
    "auth.exploringValleys": "मान्छेहरू साइकलमा घाटीहरू अन्वेषण गर्दै",
    "auth.joinValleyAdventure": "घाटी साहसिकमा सामेल हुनुहोस्",
    "auth.createAccountToStart": "सुरु गर्न आफ्नो खाता सिर्जना गर्नुहोस्",
    "auth.byCreatingAccount": "खाता सिर्जना गरेर, तपाईं हाम्रो",
    "auth.termsOfService": "सेवा नियमहरू",
    "auth.and": "र",
    "auth.privacyPolicy": "गोपनीयता नीति",

    // Homepage
    "home.title": "PedalNepal मा स्वागत छ",
    "home.subtitle": "तपाईंको विश्वसनीय साइकल भाडा सेवा",
    "home.getStarted": "सुरु गर्नुहोस्",
    "home.learnMore": "थप जान्नुहोस्",
    "home.features": "विशेषताहरू",
    "home.about": "बारेमा",
    "home.contact": "सम्पर्क",
    "home.exploreNepal": "नेपाल अन्वेषण गर्नुहोस्",
    "home.onTwoWheels": "दुई पाङ्ग्राममा",
    "home.description":
      "नेपालको सुन्दर घाटीहरू, प्राचीन मन्दिरहरू र विश्वस्त संस्कृतिको अन्वेषण गर्न हाम्रो प्रीमियम साइकल भाडा सेवाको माध्यमले।",
    "home.adventureAwaits": "प्रत्येक छलावारमा साहसिकता छ!",
    "home.manageActiveRental": "सक्रिय भाडा प्रबंधन गर्नुहोस्",
    "home.activeRental": "सक्रिय भाडा:",
    "home.rentalOverdue":
      "तपाईंको भाडा {hours} घण्टा ढिलो छ। कृपया तपाईंको वर्तमान सवारी समाप्त गर्नुहोस्।",
    "home.hasActiveRental":
      "तपाईंले एक सक्रिय भाडा छ। कृपया तपाईंको वर्तमान सवारी समाप्त गर्नुहोस्।",
    "home.dailyRentalOverdue":
      "तपाईंको दैनिक भाडा {hours} घण्टा ढिलो छ। कृपया तपाईंको वर्तमान सवारी समाप्त गर्नुहोस्।",
    "home.hasActiveDailyRental":
      "तपाईंले एक सक्रिय दैनिक भाडा छ। कृपया तपाईंको वर्तमान सवारी समाप्त गर्नुहोस्।",
    "home.payAsYouGoOverdue":
      "तपाईंको जति प्रयोग गर्ने भाडा {hours} घण्टा ढिलो छ। कृपया तपाईंको वर्तमान सवारी समाप्त गर्नुहोस्।",
    "home.hasActivePayAsYouGo":
      "तपाईंले एक सक्रिय जति प्रयोग गर्ने भाडा छ। कृपया तपाईंको वर्तमान सवारी समाप्त गर्नुहोस्।",
    "home.redirectingToAdmin": "एडमिन ड्यासबोर्डमा पुनः लोड गर्दै...",

    // Bike Selection
    "bike.title": "आफ्नो साइकल छान्नुहोस्",
    "bike.available": "उपलब्ध",
    "bike.occupied": "कब्जा गरिएको",
    "bike.reserved": "आरक्षित",
    "bike.maintenance": "मर्मतमा",
    "bike.rate": "दर",
    "bike.perHour": "प्रति घण्टा",
    "bike.selectSlot": "स्लट छान्नुहोस्",
    "bike.rentBike": "साइकल भाडामा लिनुहोस्",
    "bike.slot": "स्लट",
    "bike.availableBikes": "उपलब्ध साइकलहरू",
    "bike.findPerfectRide":
      "घाटी अन्वेषण गर्न आफ्नो उत्तम सवारी फेला पार्नुहोस्",
    "bike.availableSlots": "उपलब्ध स्लटहरू",
    "bike.rentNow": "अहिले भाडामा लिनुहोस्",
    "bike.yourCredits": "तपाईंको क्रेडिटहरू",
    "bike.station": "स्टेशन",
    "bike.km": "कि.मि.",
    "bike.perDay": "/दिन",

    // Bike Selection
    "bikeSelection.title": "आफ्नो साइकल छान्नुहोस्",
    "bikeSelection.station": "स्टेशन",
    "bikeSelection.selectSlot": "साइकल भाडामा लिन स्लट छान्नुहोस्",
    "bikeSelection.rentalDuration": "भाडा अवधि",
    "bikeSelection.hourly": "घण्टामा",
    "bikeSelection.daily": "दैनिक",
    "bikeSelection.payAsYouGo": "जति प्रयोग गर्नुहुन्छ त्यति तिर्नुहोस्",
    "bikeSelection.hours": "घण्टाहरू",
    "bikeSelection.hour": "घण्टा",
    "bikeSelection.termsAgreement": "म नियम र सर्तहरूमा सहमत छु",
    "bikeSelection.confirmRental": "भाडा पुष्टि गर्नुहोस्",
    "bikeSelection.cancel": "रद्द गर्नुहोस्",
    "bikeSelection.slot": "स्लट",
    "bikeSelection.available": "उपलब्ध",
    "bikeSelection.occupied": "कब्जा गरिएको",
    "bikeSelection.reserved": "आरक्षित",
    "bikeSelection.maintenance": "मर्मतमा",
    "bikeSelection.chooseSlots": "उपलब्ध स्लटहरूबाट छान्नुहोस्",
    "bikeSelection.selectRentalOption": "भाडा विकल्प छान्नुहोस्",
    "bikeSelection.flexiRide": "फ्लेक्सी राइड",
    "bikeSelection.payOnlyForTimeUsed":
      "प्रयोग गरेको समयको लागि मात्र तिर्नुहोस्",
    "bikeSelection.fixedRide": "फिक्स्ड राइड",
    "bikeSelection.prepaidHourlyRental": "पहिले तिरेको घण्टाको भाडा",
    "bikeSelection.selectNumberOfHours": "घण्टाहरूको संख्या छान्नुहोस्",
    "bikeSelection.quickSelect": "छिटो छान्नुहोस्",
    "bikeSelection.upfrontCost": "अग्रिम लागत",
    "bikeSelection.rate": "दर",
    "bikeSelection.chargedWhenRideEnds": "सवारी समाप्त हुँदा लाग्ने",
    "bikeSelection.noUpfrontPaymentRequired":
      "कुनै अग्रिम भुक्तानी आवश्यक छैन! तपाईंले प्रयोग गर्नुभएको समयको लागि मात्र तिर्नुहुन्छ।",
    "bikeSelection.rentalPrice": "भाडा मूल्य",
    "bikeSelection.yourCredits": "तपाईंको क्रेडिटहरू",
    "bikeSelection.remainingCredits": "बाँकी क्रेडिटहरू",
    "bikeSelection.insufficientCredits":
      "अपर्याप्त क्रेडिटहरू! तपाईंलाई यो भाडाको लागि आवश्यक छ",
    "bikeSelection.forThisRental": "यो भाडाको लागि",
    "bikeSelection.minimumCreditsRequired":
      "घण्टाको भाडाहरूको लागि न्यूनतम रू२५ क्रेडिटहरू आवश्यक छन्।",
    "bikeSelection.safetyNotes": "सुरक्षा नोटहरू",
    "bikeSelection.safetyNote1":
      "सधैं हेलमेट लगाउनुहोस् र स्थानीय यातायात नियमहरू पालना गर्नुहोस्।",
    "bikeSelection.safetyNote2":
      "सवारी गर्नुअघि ब्रेक, टायरहरू जाँच गर्नुहोस्।",
    "bikeSelection.safetyNote3":
      "सुरक्षित, अनुमत क्षेत्रहरूमा मात्र सवारी गर्नुहोस्; सबै संकेतहरू पालना गर्नुहोस्।",
    "bikeSelection.termsAndCondition": "नियम र सर्तहरू",
    "bikeSelection.termsNote1":
      "पेडल नेपाल साइकल प्रयोगबाट हुन सक्ने दुर्घटना, चोटपटक वा क्षतिको लागि जिम्मेवार छैन।",
    "bikeSelection.termsNote2":
      "सवारीहरूले सबै जोखिम लिन्छन् र असुरक्षित वा अवैध सवारीको कारण हुन सक्ने जरिवाना/कानूनी परिणामहरूको लागि जिम्मेवार छन्।",
    "bikeSelection.termsNote3":
      "कम्पनीले उपलब्धता, प्रदर्शन वा निर्बाध सेवाको ग्यारेन्टी दिन्छैन।",
    "bikeSelection.agreeToTerms":
      "मैले सबै सुरक्षा नोटहरू र प्रस्तुत गरिएका नियमहरू पढेको र सहमत भएको छु",
    "bikeSelection.termsAcknowledgment":
      "यो बक्स चेक गरेर, तपाईंले सुरक्षा आवश्यकताहरू बुझ्नुभएको र भाडा सेवाका सबै नियम र सर्तहरू स्वीकार गर्नुभएको स्वीकार गर्नुहुन्छ।",
    "bikeSelection.pleaseAgreeToTerms": "कृपया नियमहरूमा सहमत हुनुहोस्",

    // Rental
    "rental.confirm": "भाडा पुष्टि गर्नुहोस्",
    "rental.details": "भाडा विवरण",
    "rental.startTime": "सुरु समय",
    "rental.endTime": "समाप्ति समय",
    "rental.duration": "अवधि",
    "rental.cost": "लागत",
    "rental.confirmRental": "भाडा पुष्टि गर्नुहोस्",
    "rental.rentalConfirmed": "भाडा पुष्टि गरियो",
    "rental.rentalSuccess": "तपाईंको भाडा पुष्टि गरियो!",

    // Return Bike
    "return.title": "साइकल फिर्ता गर्नुहोस्",
    "return.selectStation": "स्टेशन छान्नुहोस्",
    "return.selectSlot": "फिर्ता स्लट छान्नुहोस्",
    "return.availableForReturn": "फिर्ताको लागि उपलब्ध",
    "return.endRide": "मेरो सवारी समाप्त गर्नुहोस्",
    "return.returnConfirmed": "फिर्ता पुष्टि गरियो",
    "return.returnSuccess": "तपाईंको साइकल सफलतापूर्वक फिर्ता गरियो!",
    "return.rentAnother": "अर्को साइकल भाडामा लिनुहोस्",
    "return.goHome": "घर जानुहोस्",
    "return.returnLocation": "फिर्ता स्थान",
    "return.deductedFromCredits": "तपाईंको क्रेडिटहरूबाट कटौती गरियो",
    "return.remainingCredits": "बाँकी क्रेडिटहरू",
    "return.thankYouMessage": "pedalNepal प्रयोग गर्नुभएकोमा धन्यवाद!",
    "return.additionalInfo":
      "तपाईंको साइकल सुरक्षित रूपमा फिर्ता गरियो। तपाईं अब कुनै पनि स्टेशनबाट अर्को साइकल भाडामा लिन सक्नुहुन्छ वा आफ्नो प्रोफाइलमा सवारी इतिहास जाँच गर्न सक्नुहुन्छ।",

    // My Rentals
    "rentals.title": "मेरा भाडाहरू",
    "rentals.history": "भाडा इतिहास",
    "rentals.active": "सक्रिय भाडाहरू",
    "rentals.completed": "पूर्ण भाडाहरू",
    "rentals.noRentals": "कुनै भाडा फेला परेनन्",
    "rentals.status": "स्थिति",
    "rentals.cancelled": "रद्द",
    "rentals.loadingRentals": "तपाईंका भाडाहरू लोड गर्दै...",
    "rentals.noRentalsYet": "अहिलेसम्म कुनै भाडा छैन",
    "rentals.noRentalsMessage":
      "तपाईंले अहिलेसम्म कुनै साइकल भाडामा लिनुभएको छैन। आज आफ्नो साहसिक यात्रा सुरु गर्नुहोस्!",
    "rentals.rentABike": "साइकल भाडामा लिनुहोस्",
    "rentals.trackActivities": "आफ्ना साइकल भाडा गतिविधिहरू ट्र्याक गर्नुहोस्",
    "rentals.totalSpent": "कुल खर्च",
    "rentals.recentTop5": "हालैका शीर्ष ५",
    "rentals.totalRentals": "कुल भाडाहरू",
    "rentals.allRentals": "सबै भाडाहरू",
    "rentals.recent": "हालैका",
    "rentals.rentalId": "भाडा आईडी",
    "rentals.locationDetails": "स्थान विवरण",
    "rentals.rentalInfo": "भाडा जानकारी",
    "rentals.period": "अवधि",
    "rentals.timeAndCost": "समय र लागत",
    "rentals.showing": "देखाइँदै",
    "rentals.to": "देखि",
    "rentals.of": "मध्ये",
    "rentals.rentals": "भाडाहरू",
    "rentals.rentAnotherBike": "अर्को साइकल भाडामा लिनुहोस्",
    "rentals.hour": "घण्टा",
    "rentals.hours": "घण्टाहरू",
    "rentals.calculatedOnReturn": "फिर्तामा गणना गरिने",
    "rentals.overdue": "ढिलो भयो",
    "rentals.totalPayment": "कुल भुक्तानी",
    "rentals.paymentAmount": "भुक्तानी रकम",

    // Admin Dashboard
    "admin.dashboard": "एडमिन ड्यासबोर्ड",
    "admin.overview": "अवलोकन",
    "admin.users": "प्रयोगकर्ताहरू",
    "admin.stations": "स्टेशनहरू",
    "admin.reviews": "समीक्षाहरू",
    "admin.bicycles": "साइकलहरू",
    "admin.addUser": "प्रयोगकर्ता थप्नुहोस्",
    "admin.addStation": "स्टेशन थप्नुहोस्",
    "admin.manageSlots": "स्लटहरू व्यवस्थापन गर्नुहोस्",
    "admin.totalUsers": "कुल प्रयोगकर्ताहरू",
    "admin.activeUsers": "सक्रिय प्रयोगकर्ताहरू",
    "admin.totalStations": "कुल स्टेशनहरू",
    "admin.totalBikes": "कुल साइकलहरू",
    "admin.availableBikes": "उपलब्ध साइकलहरू",
    "admin.rentedBikes": "भाडामा लिइएका साइकलहरू",
    "admin.maintenanceBikes": "मर्मतमा रहेका साइकलहरू",
    "admin.reservedSlots": "आरक्षित स्लटहरू",
    "admin.reviewsComplaints": "समीक्षा र शिकायतहरू",
    "admin.addNewUser": "नयाँ प्रयोगकर्ता थप्नुहोस्",
    "admin.createNewUserAccount": "नयाँ प्रयोगकर्ता खाता सिर्जना गर्नुहोस्",
    "admin.userInformation": "प्रयोगकर्ता जानकारी",
    "admin.fillUserDetails":
      "नयाँ प्रयोगकर्ता खाता सिर्जना गर्न विवरणहरू भर्नुहोस्",
    "admin.username": "प्रयोगकर्ता नाम",
    "admin.enterUsername": "प्रयोगकर्ता नाम प्रविष्ट गर्नुहोस्",
    "admin.enterEmail": "इमेल ठेगाना प्रविष्ट गर्नुहोस्",
    "admin.enterPassword": "पासवर्ड प्रविष्ट गर्नुहोस्",
    "admin.enterMobile": "मोबाइल नम्बर प्रविष्ट गर्नुहोस्",
    "admin.fullName": "पूरा नाम",
    "admin.enterFullName": "पूरा नाम प्रविष्ट गर्नुहोस्",
    "admin.regularUser": "सामान्य प्रयोगकर्ता",
    "admin.administrator": "प्रशासक",
    "admin.creating": "सिर्जना गर्दै...",
    "admin.createUser": "प्रयोगकर्ता सिर्जना गर्नुहोस्",
    "admin.mobileExists": "मोबाइल नम्बर पहिले नै अवस्थित छ!",
    "admin.userCreated": "प्रयोगकर्ता सफलतापूर्वक सिर्जना गरियो!",
    "admin.createUserFailed": "प्रयोगकर्ता सिर्जना गर्न असफल",
    "admin.addNewStation": "नयाँ स्टेशन थप्नुहोस्",
    "admin.manageStationsAndPricing":
      "स्टेशनहरू र मूल्य निर्धारण व्यवस्थापन गर्नुहोस्",
    "admin.manageStations": "स्टेशनहरू व्यवस्थापन गर्नुहोस्",
    "admin.stationInformation": "स्टेशन जानकारी",
    "admin.fillStationDetails": "नयाँ स्टेशन सिर्जना गर्न विवरणहरू भर्नुहोस्",
    "admin.enterStationName": "स्टेशन नाम प्रविष्ट गर्नुहोस्",
    "admin.enterLocation": "स्थान प्रविष्ट गर्नुहोस्",
    "admin.numberOfBikes": "साइकलहरूको संख्या",
    "admin.enterNumberOfBikes": "साइकलहरूको संख्या प्रविष्ट गर्नुहोस्",
    "admin.bikesToAdd": "यो स्टेशनमा थप्ने साइकलहरूको संख्या (१-५०)",
    "admin.initialStatus": "प्रारम्भिक स्थिति",
    "admin.allBikesAvailable": "सबै साइकलहरू उपलब्ध रूपमा सुरु हुन्छन्",
    "admin.setPricingForStation":
      "यो स्टेशनको लागि मूल्य निर्धारण सेट गर्नुहोस्",
    "admin.hourlyRate": "घण्टाको दर",
    "admin.dailyRate": "दैनिक दर",
    "admin.cancelEdit": "सम्पादन रद्द गर्नुहोस्",
    "admin.updating": "अपडेट गर्दै...",
    "admin.updateStation": "स्टेशन अपडेट गर्नुहोस्",
    "admin.createStation": "स्टेशन सिर्जना गर्नुहोस्",
    "admin.manageSlotsAndPricing":
      "स्लटहरू, मूल्य निर्धारण र स्टेशन कार्यहरू व्यवस्थापन गर्नुहोस्",
    "admin.resetToDefaults": "डिफल्टमा रिसेट गर्नुहोस्",
    "admin.defaultPricing": "डिफल्ट: रू२५/घण्टा, रू२५०/दिन",
    "admin.saveAllChanges": "सबै परिवर्तनहरू सुरक्षित गर्नुहोस्",
    "admin.confirmDeleteStation":
      'के तपाईं स्टेशन "{stationName}" र यसका सबै साइकलहरू मेटाउन निश्चित हुनुहुन्छ?',
    "admin.stationDeleted": "स्टेशन सफलतापूर्वक मेटाइयो!",
    "admin.deleteStationFailed":
      "स्टेशन मेटाउन असफल। कृपया फेरि प्रयास गर्नुहोस्।",
    "admin.stationUpdated": "स्टेशन सफलतापूर्वक अपडेट गरियो!",
    "admin.stationCreated": "स्टेशन सफलतापूर्वक सिर्जना गरियो!",
    "admin.createStationFailed":
      "स्टेशन सिर्जना गर्न असफल। कृपया फेरि प्रयास गर्नुहोस्।",
    "admin.totalRentals": "कुल भाडाहरू",
    "admin.recentActivity": "हालैका गतिविधिहरू",
    "admin.newUserRegistered": "नयाँ प्रयोगकर्ता दर्ता गरियो",
    "admin.allStatus": "सबै स्थिति",
    "admin.inactiveUsers": "निष्क्रिय प्रयोगकर्ताहरू",
    "admin.adminUsers": "एडमिन प्रयोगकर्ताहरू",
    "admin.statusActive": "सक्रिय",
    "admin.statusInactive": "निष्क्रिय",
    "admin.statusAdmin": "एडमिन",
    "admin.bikeStatusTitle": "सबै स्टेशनहरूको साइकल स्थिति",
    "admin.bikeStatusDescription": "सबै स्टेशनहरूमा कुल साइकलहरू",
    "admin.userActivityTitle": "प्रयोगकर्ता गतिविधि",
    "admin.userActivityDescription": "प्रयोगकर्ता संलग्नताको विवरण",
    "admin.userManagement": "प्रयोगकर्ता व्यवस्थापन",
    "admin.stationManagement": "स्टेशन व्यवस्थापन",
    "admin.serialNumber": "क्र.सं.",
    "admin.name": "नाम",
    "admin.status": "स्थिति",
    "admin.rides": "सवारीहरू",
    "admin.station": "स्टेशन",
    "admin.duration": "अवधि",
    "admin.credits": "क्रेडिटहरू",
    "admin.spent": "खर्च",
    "admin.actions": "कार्यहरू",
    "admin.stationName": "स्टेशन नाम",
    "admin.location": "स्थान",
    "admin.totalSlots": "कुल स्लटहरू",
    "admin.inMaintenance": "मर्मतमा",
    "admin.availableSlots": "उपलब्ध स्लटहरू",
    "admin.loadingDashboard": "एडमिन ड्यासबोर्ड लोड गर्दै...",
    "admin.accessDenied": "पहुँच अस्वीकृत",
    "admin.noPermission": "तपाईंसँग एडमिन ड्यासबोर्डमा पहुँच गर्ने अनुमति छैन।",
    "admin.goToHome": "घर जानुहोस्",
    "admin.managePaddleNepal": "पेडलनेपाल व्यवस्थापन गर्नुहोस्",
    "admin.currentlyActive": "हाल सक्रिय",
    "admin.emptySlots": "खाली स्लटहरू",
    "admin.rented": "भाडामा लिइएको",
    "admin.empty": "खाली",
    "admin.available": "उपलब्ध",
    "admin.filterByName": "नामद्वारा फिल्टर गर्नुहोस्",
    "admin.filterByStatus": "स्थितिद्वारा फिल्टर गर्नुहोस्",
    "admin.filterByNameLocation": "नाम/स्थानद्वारा फिल्टर गर्नुहोस्",
    "admin.add": "थप्नुहोस्",
    "admin.admin": "एडमिन",
    "admin.remove": "हटाउनुहोस्",
    "admin.delete": "मेटाउनुहोस्",
    "admin.edit": "सम्पादन गर्नुहोस्",
    "admin.addCredits": "क्रेडिटहरू थप्नुहोस्",
    "admin.addCreditsToUser": "प्रयोगकर्ता खातामा क्रेडिटहरू थप्नुहोस्",
    "admin.creditsToAdd": "थप्ने क्रेडिटहरू",
    "admin.currentCredits": "हालको क्रेडिटहरू",
    "admin.newBalance": "नयाँ ब्यालेन्स",
    "admin.addCreditsButton": "क्रेडिटहरू थप्नुहोस्",
    "admin.cancel": "रद्द गर्नुहोस्",
    "admin.maintenance": "मर्मत",
    "admin.noStationsFound": "कुनै स्टेशन फेला परेनन्",
    "admin.noStationsMessage":
      "तपाईंको फिल्टरहरूसँग मेल खाने कुनै स्टेशन उपलब्ध छैन।",
    "admin.returningUsers": "फिर्ता आउने प्रयोगकर्ताहरू",
    "admin.newUsers": "नयाँ प्रयोगकर्ताहरू",
    "admin.manageSlotsTitle": "स्लटहरू व्यवस्थापन गर्नुहोस्",
    "admin.editStationTitle": "स्टेशन सम्पादन गर्नुहोस्",
    "admin.deleteStationTitle": "स्टेशन मेटाउनुहोस्",
    "admin.perHour": "प्रति घण्टा",
    "admin.perDay": "प्रति दिन",
    "admin.slotStatus": "स्लट स्थिति",
    "admin.occupied": "कब्जा गरिएको",
    "admin.currentPricing": "हालको मूल्य निर्धारण",
    "admin.hourly": "घण्टामा",
    "admin.daily": "दैनिक",

    // User Management
    "users.title": "प्रयोगकर्ता व्यवस्थापन",
    "users.addUser": "नयाँ प्रयोगकर्ता थप्नुहोस्",
    "users.editUser": "प्रयोगकर्ता सम्पादन गर्नुहोस्",
    "users.deleteUser": "प्रयोगकर्ता मेटाउनुहोस्",
    "users.name": "नाम",
    "users.email": "इमेल",
    "users.role": "भूमिका",
    "users.status": "स्थिति",
    "users.actions": "कार्यहरू",
    "users.admin": "एडमिन",
    "users.user": "प्रयोगकर्ता",
    "users.active": "सक्रिय",
    "users.inactive": "निष्क्रिय",

    // Station Management
    "stations.title": "स्टेशन व्यवस्थापन",
    "stations.addStation": "नयाँ स्टेशन थप्नुहोस्",
    "stations.editStation": "स्टेशन सम्पादन गर्नुहोस्",
    "stations.deleteStation": "स्टेशन मेटाउनुहोस्",
    "stations.name": "स्टेशन नाम",
    "stations.location": "स्थान",
    "stations.address": "ठेगाना",
    "stations.slots": "स्लटहरू",
    "stations.actions": "कार्यहरू",

    // Slot Management
    "slots.title": "स्लट व्यवस्थापन",
    "slots.available": "उपलब्ध",
    "slots.occupied": "कब्जा गरिएको",
    "slots.reserved": "फिर्ताको लागि आरक्षित",
    "slots.maintenance": "मर्मतमा",
    "slots.changeStatus": "स्थिति परिवर्तन गर्नुहोस्",
    "slots.resetSlots": "१० स्लटमा रिसेट गर्नुहोस्",
    "slots.confirmStatusChange":
      "के तपाईं स्थिति परिवर्तन गर्न निश्चित हुनुहुन्छ?",
    "slots.confirmReset": "के तपाईं सबै स्लटहरू रिसेट गर्न निश्चित हुनुहुन्छ?",

    // Reviews Management
    "reviews.title": "समीक्षा व्यवस्थापन",
    "reviews.all": "सबै",
    "reviews.reviews": "समीक्षाहरू",
    "reviews.complaints": "शिकायतहरू",
    "reviews.search": "समीक्षाहरू खोज्नुहोस्...",
    "reviews.rating": "मूल्यांकन",
    "reviews.comment": "टिप्पणी",
    "reviews.type": "प्रकार",
    "reviews.date": "मिति",
    "reviews.noReviews": "कुनै समीक्षा फेला परेनन्",
    "reviews.manageFeedback":
      "ग्राहकको प्रतिक्रिया र शिकायतहरू व्यवस्थापन गर्नुहोस्",
    "reviews.searchReviews": "समीक्षा र शिकायतहरू खोज्नुहोस्...",
    "reviews.user": "प्रयोगकर्ता",
    "reviews.station": "स्टेशन",
    "reviews.actions": "कार्यहरू",
    "reviews.view": "हेर्नुहोस्",
    "reviews.reply": "जवाफ दिनुहोस्",
    "reviews.review": "समीक्षा",
    "reviews.complaint": "शिकायत",

    // Language
    "language.english": "English",
    "language.nepali": "नेपाली",
    "language.switch": "भाषा परिवर्तन गर्नुहोस्",

    // Profile
    "profile.activeUser": "सक्रिय प्रयोगकर्ता",
    "profile.personalInformation": "व्यक्तिगत जानकारी",
    "profile.name": "नाम",
    "profile.email": "इमेल",
    "profile.mobile": "मोबाइल",
    "profile.credits": "क्रेडिटहरू",
    "profile.rentalsAvailable": "भाडाहरू उपलब्ध",
    "profile.changePassword": "पासवर्ड परिवर्तन गर्नुहोस्",
    "profile.oldPassword": "पुरानो पासवर्ड",
    "profile.newPassword": "नयाँ पासवर्ड",
    "profile.updateSuccess": "प्रोफाइल सफलतापूर्वक अपडेट गरियो!",
    "profile.updateFailed":
      "प्रोफाइल अपडेट गर्न असफल। कृपया फेरि प्रयास गर्नुहोस्।",
    "profile.updateError": "एउटा त्रुटि भयो। कृपया फेरि प्रयास गर्नुहोस्।",
    "profile.fillBothFields": "कृपया दुवै फिल्डहरू भर्नुहोस्।",
    "profile.passwordChanged": "पासवर्ड सफलतापूर्वक परिवर्तन गरियो!",
    "profile.oldPasswordIncorrect": "पुरानो पासवर्ड गलत छ।",
    "profile.digitalWallet": "डिजिटल वालेट",
    "profile.manageWallet": "वालेट प्रबंधन गर्नुहोस्",
    "profile.availableBalance": "उपलब्ध रकम",

    // Footer
    "footer.home": "घर",
    "footer.wallet": "वालेट (चाँडै आउँदै)",
    "footer.myRentals": "मेरा भाडाहरू",
    "footer.qrScanner": "QR स्क्यानर",
    "footer.availableBikes": "उपलब्ध साइकलहरू",
    "footer.profile": "प्रोफाइल",
    "footer.logout": "लगआउट",
    "footer.digitalWallet": "डिजिटल वालेट",
    "footer.managePaymentMethods":
      "आफ्ना भुक्तानी विधिहरू व्यवस्थापन गर्नुहोस्",
    "footer.availableBalance": "उपलब्ध ब्यालेन्स",
    "footer.addMoney": "पैसा थप्नुहोस्",
    "footer.transactionHistory": "लेनदेन इतिहास",
    "footer.scanBikeQRCode": "साइकल भाडामा लिन QR कोड स्क्यान गर्नुहोस्",
    "footer.startingCamera": "क्यामेरा सुरु गर्दै...",
    "footer.cameraError": "क्यामेरा त्रुटि",
    "footer.tryAgain": "फेरि प्रयास गर्नुहोस्",
    "footer.cameraReadyToScan": "स्क्यान गर्न क्यामेरा तयार छ",
    "footer.scanning": "स्क्यान गर्दै...",
    "footer.stopScanning": "स्क्यान रोक्नुहोस्",
    "footer.startCamera": "क्यामेरा सुरु गर्नुहोस्",
    "footer.selectStationManually": "स्टेशन म्यानुअली छान्नुहोस्",

    // Error
    "error.somethingWentWrong": "केही गलत भयो!",
    "error.unexpectedError":
      "हामी माफी चाहन्छौं, तर यो पृष्ठ लोड गर्दै केही अनपेक्षित घटना घट्यो।",
    "error.tryAgain": "फेरि प्रयास गर्नुहोस्",
    "error.goToHome": "घर जानुहोस्",
    "error.errorDetails": "त्रुटि विवरण (विकास)",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    // Load saved language preference
    const savedLanguage = localStorage.getItem(
      "pedalnepal_language",
    ) as Language;
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "ne")) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("pedalnepal_language", lang);
  };

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
